In [98]:
import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)
import seaborn as sns
import matplotlib.pyplot as plt
sns.set(style="darkgrid")
# plt.style.use("seaborn-pastel")

df = pd.read_excel(r"G:\harvard project\New Microsoft Excel Worksheet.xlsx")
df.head()

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6
0,Age,Silver,Bronze,Athlete,Date,Gold,Sport
1,0,0,0,Michael Phelps,2008-08-24 00:00:00,8,Swimming
2,19,0,2,Michael Phelps,2004-08-29 00:00:00,6,Swimming
3,27,2,0,Michael Phelps,2012-08-12 00:00:00,4,Swimming
4,25,2,3,Natalie Coughlin,2008-08-24 00:00:00,1,Swimming

In [128]:
gb=df.groupby("Athlete")["Gold"].sum()
print(gb)

Athlete
Aleksey Nemov                    2
Alicia Coutts                    1
Aliya Mustafina                  1
Allison Schmitt                  3
An Hyeon-Su                      3
Athlete                      Gold
Cindy Klassen                    1
Dara Torres                      2
Dmitry Sautin                    1
Gary Hall Jr.                    2
Ian Thorpe                       5
Inge de Bruijn                   4
Jenny Thompson                   3
Kirsty Coventry                  1
Leontien Zijlaard                3
Libby Lenton-Trick               2
Marit Bjørgen                    3
Michael Klim                     2
Michael Phelps                  18
Missy Franklin                   4
Nastia Liukin                    1
Natalie Coughlin                 3
Ole Einar Bjørndalen             4
Petria Thomas                    3
Petter Northug Jr.               2
Pieter van den Hoogenband        2
Ryan Lochte                      4
Shawn Johnson                    1
Sun Yang                         2
Susie O'Neill                    1
Name: Gold, dtype: object

In [138]:
gb.plot(kind="pie",
                 autopct="%.0f%%",  # Percentage format
                 figsize=(10, 10),  # Size of the figure
                 wedgeprops=dict(width=0.4),  # Thickness of the pie
                 pctdistance=0.85)  # Position of percentage labels

# Formatting the plot
plt.ylabel('')  # Removing y-axis label
plt.title("Gold Medal Distribution Among Athletes", fontweight="bold")  # Title

# Display the plot
plt.show()

TypeError: '<' not supported between instances of 'str' and 'int'